---
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        name: Ensure that no large files are committed
        args:
          - --maxkb=4096
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      # - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint
        description: This hook runs yamllint.
        entry: yamllint
        exclude: |
            (?x)(
                ^tests/
                )
        types: [file]
        files: \.(yaml|yml)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.36.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=100
